class HadithModel {
  final String arabic;
  final Map<String, String> translations;
  final String source;
  final String narrator;

  const HadithModel({
    required this.arabic,
    required this.translations,
    required this.source,
    required this.narrator,
  });

  static const List<HadithModel> hadiths = [
    HadithModel(
      arabic: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى',
      translations: {
        'en': 'Actions are judged by intentions, and every person will get what they intended.',
        'tr': 'Ameller niyetlere göredir ve herkes niyet ettiğini elde eder.',
        'ar': 'إنما الأعمال بالنيات وإنما لكل امرئ ما نوى',
        'ru': 'Дела оцениваются по намерениям, и каждый получит то, что намеревался.',
        'hi': 'कर्म नीयतों पर निर्भर हैं, और हर व्यक्ति को वही मिलेगा जो उसने नीयत किया।',
        'id': 'Sesungguhnya setiap amalan tergantung pada niatnya, dan setiap orang akan mendapatkan apa yang ia niatkan.',
        'zh': '行为取决于意念，每个人将得到他所意念的。',
        'de': 'Taten werden nach Absichten beurteilt, und jeder Mensch bekommt, was er beabsichtigt hat.',
        'nl': 'Daden worden beoordeeld op intenties, en iedereen krijgt wat hij bedoeld heeft.',
        'fr': 'Les actes ne valent que par les intentions, et chacun n\'aura que ce qu\'il a eu l\'intention de faire.',
        'es': 'Las acciones se juzgan por las intenciones, y cada persona obtendrá lo que pretendió.',
      },
      source: 'Sahih al-Bukhari 1',
      narrator: 'Umar ibn al-Khattab (RA)',
    ),
    HadithModel(
      arabic: 'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
      translations: {
        'en': 'The best of you are those who learn the Quran and teach it.',
        'tr': 'Sizin en hayırlınız Kur\'an\'ı öğrenen ve öğretendir.',
        'ar': 'خيركم من تعلم القرآن وعلمه',
        'ru': 'Лучшие из вас — те, кто изучает Коран и обучает ему.',
        'hi': 'तुम में सबसे अच्छे वे हैं जो कुरान सीखें और सिखाएं।',
        'id': 'Sebaik-baik kalian adalah yang mempelajari Al-Quran dan mengajarkannya.',
        'zh': '你们中最好的人是学习古兰经并教授它的人。',
        'de': 'Die Besten von euch sind diejenigen, die den Quran lernen und ihn lehren.',
        'nl': 'De besten onder jullie zijn degenen die de Koran leren en onderwijzen.',
        'fr': 'Les meilleurs d\'entre vous sont ceux qui apprennent le Coran et l\'enseignent.',
        'es': 'Los mejores de ustedes son quienes aprenden el Corán y lo enseñan.',
      },
      source: 'Sahih al-Bukhari 5027',
      narrator: 'Uthman ibn Affan (RA)',
    ),
    HadithModel(
      arabic: 'لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
      translations: {
        'en': 'None of you truly believes until he loves for his brother what he loves for himself.',
        'tr': 'Sizden biriniz kendisi için istediğini kardeşi için de istemedikçe gerçek mümin olamaz.',
        'ar': 'لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه',
        'ru': 'Не уверует никто из вас, пока не полюбит для брата своего то, что любит для себя.',
        'hi': 'तुम में से कोई तब तक सच्चा मोमिन नहीं जब तक अपने भाई के लिए वही न चाहे जो अपने लिए चाहता है।',
        'id': 'Tidak beriman seseorang di antara kalian hingga ia mencintai saudaranya seperti mencintai dirinya sendiri.',
        'zh': '你们中没有人真正信仰，直到他为兄弟喜爱他为自己所喜爱的。',
        'de': 'Keiner von euch glaubt wahrhaft, bis er für seinen Bruder liebt, was er für sich selbst liebt.',
        'nl': 'Niemand van jullie gelooft werkelijk totdat hij voor zijn broeder wenst wat hij voor zichzelf wenst.',
        'fr': 'Aucun d\'entre vous ne croit vraiment tant qu\'il n\'aime pas pour son frère ce qu\'il aime pour lui-même.',
        'es': 'Ninguno de ustedes cree verdaderamente hasta que ame para su hermano lo que ama para sí mismo.',
      },
      source: 'Sahih al-Bukhari 13',
      narrator: 'Anas ibn Malik (RA)',
    ),
    HadithModel(
      arabic: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
      translations: {
        'en': 'Whoever believes in Allah and the Last Day, let him speak good or remain silent.',
        'tr': 'Allah\'a ve ahiret gününe iman eden kimse ya hayır söylesin ya da sussun.',
        'ar': 'من كان يؤمن بالله واليوم الآخر فليقل خيراً أو ليصمت',
        'ru': 'Кто верует в Аллаха и Судный день, пусть говорит благое или молчит.',
        'hi': 'जो अल्लाह और आखिरत के दिन पर ईमान रखता है, वह अच्छी बात कहे या चुप रहे।',
        'id': 'Barangsiapa beriman kepada Allah dan hari akhir, hendaklah ia berkata baik atau diam.',
        'zh': '谁信仰真主和末日，就让他说善言或沉默。',
        'de': 'Wer an Allah und den Jüngsten Tag glaubt, soll Gutes sprechen oder schweigen.',
        'nl': 'Wie in Allah en de Laatste Dag gelooft, laat hem goed spreken of zwijgen.',
        'fr': 'Quiconque croit en Allah et au Jour dernier, qu\'il dise du bien ou qu\'il se taise.',
        'es': 'Quien crea en Allah y el Último Día, que diga algo bueno o guarde silencio.',
      },
      source: 'Sahih al-Bukhari 6018',
      narrator: 'Abu Hurairah (RA)',
    ),
    HadithModel(
      arabic: 'الدُّنْيَا سِجْنُ الْمُؤْمِنِ وَجَنَّةُ الْكَافِرِ',
      translations: {
        'en': 'The world is a prison for the believer and a paradise for the disbeliever.',
        'tr': 'Dünya müminin zindanı, kâfirin cennetidir.',
        'ar': 'الدنيا سجن المؤمن وجنة الكافر',
        'ru': 'Мир — тюрьма для верующего и рай для неверующего.',
        'hi': 'दुनिया मोमिन के लिए कैदखाना है और काफिर के लिए जन्नत है।',
        'id': 'Dunia adalah penjara bagi orang beriman dan surga bagi orang kafir.',
        'zh': '今世是信士的监狱，是不信者的乐园。',
        'de': 'Die Welt ist ein Gefängnis für den Gläubigen und ein Paradies für den Ungläubigen.',
        'nl': 'De wereld is een gevangenis voor de gelovige en een paradijs voor de ongelovige.',
        'fr': 'Le monde est une prison pour le croyant et un paradis pour le mécréant.',
        'es': 'El mundo es una prisión para el creyente y un paraíso para el incrédulo.',
      },
      source: 'Sahih Muslim 2956',
      narrator: 'Abu Hurairah (RA)',
    ),
    HadithModel(
      arabic: 'تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ',
      translations: {
        'en': 'Your smile in the face of your brother is charity.',
        'tr': 'Kardeşine gülümsemen sadakadır.',
        'ar': 'تبسمك في وجه أخيك لك صدقة',
        'ru': 'Твоя улыбка брату — это милостыня.',
        'hi': 'अपने भाई के चेहरे पर तुम्हारी मुस्कान सदका है।',
        'id': 'Senyumanmu di hadapan saudaramu adalah sedekah.',
        'zh': '你对兄弟微笑就是施舍。',
        'de': 'Dein Lächeln gegenüber deinem Bruder ist eine Spende.',
        'nl': 'Je glimlach naar je broeder is een liefdadigheid.',
        'fr': 'Ton sourire à ton frère est une aumône.',
        'es': 'Tu sonrisa ante tu hermano es una caridad.',
      },
      source: 'Jami at-Tirmidhi 1956',
      narrator: 'Abu Dharr (RA)',
    ),
    HadithModel(
      arabic: 'الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ',
      translations: {
        'en': 'A Muslim is the one from whose tongue and hands other Muslims are safe.',
        'tr': 'Müslüman, dilinden ve elinden diğer Müslümanların güvende olduğu kimsedir.',
        'ar': 'المسلم من سلم المسلمون من لسانه ويده',
        'ru': 'Мусульманин — тот, от языка и рук которого в безопасности другие мусульмане.',
        'hi': 'मुसलमान वह है जिसकी जुबान और हाथ से दूसरे मुसलमान सुरक्षित रहें।',
        'id': 'Muslim sejati adalah orang yang kaum Muslim lainnya selamat dari lisan dan tangannya.',
        'zh': '穆斯林是其他穆斯林免受其舌头和手伤害的人。',
        'de': 'Ein Muslim ist derjenige, vor dessen Zunge und Hand andere Muslime sicher sind.',
        'nl': 'Een moslim is degene van wiens tong en hand andere moslims veilig zijn.',
        'fr': 'Le musulman est celui dont les autres musulmans sont à l\'abri de sa langue et de sa main.',
        'es': 'Un musulmán es aquel de cuya lengua y manos los demás musulmanes están a salvo.',
      },
      source: 'Sahih al-Bukhari 10',
      narrator: 'Abdullah ibn Amr (RA)',
    ),
    HadithModel(
      arabic: 'إِنَّ اللَّهَ لَا يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ',
      translations: {
        'en': 'Allah does not look at your appearance or your wealth, but He looks at your hearts and your deeds.',
        'tr': 'Allah sizin suretlerinize ve mallarınıza değil, kalplerinize ve amellerinize bakar.',
        'ar': 'إن الله لا ينظر إلى صوركم وأموالكم ولكن ينظر إلى قلوبكم وأعمالكم',
        'ru': 'Аллах не смотрит на вашу внешность и богатство, но смотрит на ваши сердца и дела.',
        'hi': 'अल्लाह तुम्हारी शक्ल और दौलत नहीं देखता, बल्कि तुम्हारे दिलों और अमल को देखता है।',
        'id': 'Sesungguhnya Allah tidak melihat rupa dan harta kalian, tetapi melihat hati dan amal kalian.',
        'zh': '真主不看你们的外表和财富，而是看你们的心灵和行为。',
        'de': 'Allah schaut nicht auf euer Aussehen und euren Reichtum, sondern auf eure Herzen und Taten.',
        'nl': 'Allah kijkt niet naar jullie uiterlijk en rijkdom, maar naar jullie harten en daden.',
        'fr': 'Allah ne regarde pas votre apparence ni vos richesses, mais Il regarde vos cœurs et vos actes.',
        'es': 'Allah no mira vuestra apariencia ni vuestra riqueza, sino que mira vuestros corazones y vuestras obras.',
      },
      source: 'Sahih Muslim 2564',
      narrator: 'Abu Hurairah (RA)',
    ),
    HadithModel(
      arabic: 'اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ',
      translations: {
        'en': 'Fear Allah wherever you are, follow a bad deed with a good one to erase it, and treat people with good character.',
        'tr': 'Nerede olursan ol Allah\'tan kork, kötülüğün arkasından iyilik yap ki onu silsin ve insanlara güzel ahlakla muamele et.',
        'ar': 'اتق الله حيثما كنت وأتبع السيئة الحسنة تمحها وخالق الناس بخلق حسن',
        'ru': 'Бойся Аллаха, где бы ты ни был, за плохим делом соверши хорошее — оно сотрёт его, и обходись с людьми хорошо.',
        'hi': 'जहां भी हो अल्लाह से डरो, बुराई के बाद नेकी करो वह उसे मिटा देगी, और लोगों से अच्छे अख़लाक़ से पेश आओ।',
        'id': 'Bertakwalah kepada Allah di mana pun kamu berada, iringi keburukan dengan kebaikan niscaya ia akan menghapusnya, dan berakhlaklah baik kepada manusia.',
        'zh': '无论你在哪里都要敬畏真主，以善行跟随恶行以消除它，以良好的品德对待人们。',
        'de': 'Fürchte Allah, wo immer du bist, folge einer schlechten Tat mit einer guten, um sie auszulöschen, und behandle die Menschen mit gutem Charakter.',
        'nl': 'Vrees Allah waar je ook bent, volg een slechte daad op met een goede om het uit te wissen, en behandel mensen met goed karakter.',
        'fr': 'Crains Allah où que tu sois, fais suivre une mauvaise action d\'une bonne pour l\'effacer, et traite les gens avec bon caractère.',
        'es': 'Teme a Allah dondequiera que estés, sigue una mala acción con una buena para borrarla, y trata a la gente con buen carácter.',
      },
      source: 'Jami at-Tirmidhi 1987',
      narrator: 'Abu Dharr & Muadh ibn Jabal (RA)',
    ),
    HadithModel(
      arabic: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ طَرِيقًا إِلَى الْجَنَّةِ',
      translations: {
        'en': 'Whoever travels a path seeking knowledge, Allah will make easy for him a path to Paradise.',
        'tr': 'Kim ilim öğrenmek için bir yola girerse, Allah ona cennete giden yolu kolaylaştırır.',
        'ar': 'من سلك طريقاً يلتمس فيه علماً سهل الله له طريقاً إلى الجنة',
        'ru': 'Кто отправится в путь ради поиска знаний, Аллах облегчит ему путь в Рай.',
        'hi': 'जो इल्म की तलाश में किसी रास्ते पर चलता है, अल्लाह उसके लिए जन्नत का रास्ता आसान कर देता है।',
        'id': 'Barangsiapa menempuh jalan untuk mencari ilmu, maka Allah akan memudahkan baginya jalan menuju surga.',
        'zh': '谁踏上寻求知识的道路，真主就为他铺设通往天堂的道路。',
        'de': 'Wer einen Weg beschreitet, um Wissen zu suchen, dem erleichtert Allah einen Weg ins Paradies.',
        'nl': 'Wie een pad bewandelt op zoek naar kennis, Allah zal voor hem een pad naar het Paradijs vergemakkelijken.',
        'fr': 'Quiconque emprunte un chemin à la recherche du savoir, Allah lui facilitera un chemin vers le Paradis.',
        'es': 'Quien recorra un camino buscando conocimiento, Allah le facilitará un camino al Paraíso.',
      },
      source: 'Sahih Muslim 2699',
      narrator: 'Abu Hurairah (RA)',
    ),
    HadithModel(
      arabic: 'الدُّنْيَا سِجْنُ الْمُؤْمِنِ وَجَنَّةُ الْكَافِرِ',
      translations: {
        'en': 'The world is a prison for the believer and a paradise for the disbeliever.',
        'tr': 'Dünya mümin için zindan, kafir için cennettir.',
        'ar': 'الدنيا سجن المؤمن وجنة الكافر',
        'ru': 'Этот мир — тюрьма для верующего и рай для неверующего.',
        'hi': 'दुनिया मोमिन के लिए कैदखाना और काफिर के लिए जन्नत है।',
        'id': 'Dunia adalah penjara bagi orang beriman dan surga bagi orang kafir.',
        'zh': '今世是信士的牢狱，是不信者的乐园。',
        'de': 'Die Welt ist ein Gefängnis für den Gläubigen und ein Paradies für den Ungläubigen.',
        'nl': 'De wereld is een gevangenis voor de gelovige en een paradijs voor de ongelovige.',
        'fr': 'Ce monde est une prison pour le croyant et un paradis pour le mécréant.',
        'es': 'El mundo es una prisión para el creyente y un paraíso para el incrédulo.',
      },
      source: 'Sahih Muslim 2956',
      narrator: 'Abu Hurairah (RA)',
    ),
    HadithModel(
      arabic: 'لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
      translations: {
        'en': 'None of you truly believes until he loves for his brother what he loves for himself.',
        'tr': 'Sizden biri, kendisi için sevdiğini kardeşi için de sevmedikçe gerçek mümin olamaz.',
        'ar': 'لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه',
        'ru': 'Не уверует никто из вас, пока не полюбит для брата своего то, что любит для себя.',
        'hi': 'तुम में से कोई उस वक्त तक मोमिन नहीं हो सकता जब तक वह अपने भाई के लिए वही न चाहे जो अपने लिए चाहता है।',
        'id': 'Tidaklah beriman seseorang di antara kalian sampai dia mencintai untuk saudaranya apa yang dia cintai untuk dirinya sendiri.',
        'zh': '你们中没有人真正信仰，直到他为兄弟喜爱他为自己所喜爱的。',
        'de': 'Keiner von euch glaubt wahrhaft, bis er für seinen Bruder liebt, was er für sich selbst liebt.',
        'nl': 'Niemand van jullie gelooft werkelijk totdat hij voor zijn broeder wenst wat hij voor zichzelf wenst.',
        'fr': 'Aucun d\'entre vous ne croit véritablement tant qu\'il n\'aime pour son frère ce qu\'il aime pour lui-même.',
        'es': 'Ninguno de vosotros cree verdaderamente hasta que ame para su hermano lo que ama para sí mismo.',
      },
      source: 'Sahih al-Bukhari 13',
      narrator: 'Anas ibn Malik (RA)',
    ),
    HadithModel(
      arabic: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
      translations: {
        'en': 'Whoever believes in Allah and the Last Day, let him speak good or remain silent.',
        'tr': 'Allah\'a ve ahiret gününe iman eden, ya hayır söylesin ya da sussun.',
        'ar': 'من كان يؤمن بالله واليوم الآخر فليقل خيراً أو ليصمت',
        'ru': 'Кто верит в Аллаха и Судный день, пусть говорит благое или молчит.',
        'hi': 'जो अल्लाह और आख़िरत के दिन पर ईमान रखता है, वह अच्छी बात कहे या चुप रहे।',
        'id': 'Barangsiapa beriman kepada Allah dan hari akhir, hendaklah ia berkata baik atau diam.',
        'zh': '谁信仰真主和末日，就让他说好话或保持沉默。',
        'de': 'Wer an Allah und den Jüngsten Tag glaubt, soll Gutes sprechen oder schweigen.',
        'nl': 'Wie in Allah en de Laatste Dag gelooft, laat hem goed spreken of zwijgen.',
        'fr': 'Quiconque croit en Allah et au Jour Dernier, qu\'il dise du bien ou qu\'il se taise.',
        'es': 'Quien cree en Allah y el Último Día, que diga algo bueno o que guarde silencio.',
      },
      source: 'Sahih al-Bukhari 6018',
      narrator: 'Abu Hurairah (RA)',
    ),
    HadithModel(
      arabic: 'إِنَّ اللَّهَ لَا يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ',
      translations: {
        'en': 'Allah does not look at your appearance or wealth, but rather He looks at your hearts and deeds.',
        'tr': 'Allah sizin suretlerinize ve mallarınıza bakmaz, kalplerinize ve amellerinize bakar.',
        'ar': 'إن الله لا ينظر إلى صوركم وأموالكم ولكن ينظر إلى قلوبكم وأعمالكم',
        'ru': 'Аллах не смотрит на ваши лица и богатства, но смотрит на ваши сердца и дела.',
        'hi': 'अल्लाह तुम्हारी शक्लों और मालों को नहीं देखता, बल्कि तुम्हारे दिलों और अमलों को देखता है।',
        'id': 'Sesungguhnya Allah tidak melihat rupa dan harta kalian, tetapi Dia melihat hati dan amal kalian.',
        'zh': '真主不看你们的外貌和财富，而是看你们的心灵和行为。',
        'de': 'Allah schaut nicht auf euer Aussehen und euren Reichtum, sondern auf eure Herzen und Taten.',
        'nl': 'Allah kijkt niet naar jullie uiterlijk en bezittingen, maar naar jullie harten en daden.',
        'fr': 'Allah ne regarde ni vos apparences ni vos richesses, mais Il regarde vos cœurs et vos actes.',
        'es': 'Allah no mira vuestras apariencias ni riquezas, sino que mira vuestros corazones y obras.',
      },
      source: 'Sahih Muslim 2564',
      narrator: 'Abu Hurairah (RA)',
    ),
    HadithModel(
      arabic: 'تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ',
      translations: {
        'en': 'Your smiling in the face of your brother is an act of charity.',
        'tr': 'Kardeşinin yüzüne gülümsemen sadakadır.',
        'ar': 'تبسمك في وجه أخيك لك صدقة',
        'ru': 'Твоя улыбка брату — это милостыня.',
        'hi': 'अपने भाई के चेहरे पर तुम्हारी मुस्कान सदक़ा है।',
        'id': 'Senyummu di hadapan saudaramu adalah sedekah bagimu.',
        'zh': '你对兄弟微笑就是施舍。',
        'de': 'Dein Lächeln deinem Bruder gegenüber ist eine Wohltätigkeit.',
        'nl': 'Je glimlach naar je broeder is een vorm van liefdadigheid.',
        'fr': 'Ton sourire à ton frère est une aumône.',
        'es': 'Tu sonrisa ante tu hermano es una obra de caridad.',
      },
      source: 'Jami at-Tirmidhi 1956',
      narrator: 'Abu Dharr (RA)',
    ),
    HadithModel(
      arabic: 'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
      translations: {
        'en': 'The best of you are those who learn the Quran and teach it.',
        'tr': 'En hayırlınız Kur\'an\'ı öğrenen ve öğretendir.',
        'ar': 'خيركم من تعلم القرآن وعلمه',
        'ru': 'Лучшие из вас — те, кто изучает Коран и обучает ему.',
        'hi': 'तुम में सबसे अच्छे वो हैं जो कुरान सीखें और सिखाएं।',
        'id': 'Sebaik-baik kalian adalah yang mempelajari Al-Quran dan mengajarkannya.',
        'zh': '你们中最好的人是学习古兰经并教授它的人。',
        'de': 'Die Besten unter euch sind diejenigen, die den Quran lernen und lehren.',
        'nl': 'De besten onder jullie zijn degenen die de Koran leren en onderwijzen.',
        'fr': 'Les meilleurs d\'entre vous sont ceux qui apprennent le Coran et l\'enseignent.',
        'es': 'Los mejores de vosotros son quienes aprenden el Corán y lo enseñan.',
      },
      source: 'Sahih al-Bukhari 5027',
      narrator: 'Uthman ibn Affan (RA)',
    ),
    HadithModel(
      arabic: 'الطُّهُورُ شَطْرُ الإِيمَانِ',
      translations: {
        'en': 'Cleanliness is half of faith.',
        'tr': 'Temizlik imanın yarısıdır.',
        'ar': 'الطهور شطر الإيمان',
        'ru': 'Чистота — половина веры.',
        'hi': 'पाकीज़गी आधा ईमान है।',
        'id': 'Kebersihan adalah separuh iman.',
        'zh': '清洁是信仰的一半。',
        'de': 'Reinheit ist die Hälfte des Glaubens.',
        'nl': 'Reinheid is de helft van het geloof.',
        'fr': 'La propreté est la moitié de la foi.',
        'es': 'La limpieza es la mitad de la fe.',
      },
      source: 'Sahih Muslim 223',
      narrator: 'Abu Malik al-Ashari (RA)',
    ),
    HadithModel(
      arabic: 'الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ',
      translations: {
        'en': 'A Muslim is the one from whose tongue and hands other Muslims are safe.',
        'tr': 'Müslüman, dilinden ve elinden diğer Müslümanların güvende olduğu kimsedir.',
        'ar': 'المسلم من سلم المسلمون من لسانه ويده',
        'ru': 'Мусульманин — тот, от чьего языка и рук мусульмане в безопасности.',
        'hi': 'मुसलमान वह है जिसकी ज़बान और हाथ से दूसरे मुसलमान सुरक्षित रहें।',
        'id': 'Muslim sejati adalah orang yang kaum muslimin lainnya selamat dari lisan dan tangannya.',
        'zh': '穆斯林是其他穆斯林免受其舌头和手伤害的人。',
        'de': 'Ein Muslim ist derjenige, vor dessen Zunge und Hand andere Muslime sicher sind.',
        'nl': 'Een moslim is degene voor wiens tong en hand andere moslims veilig zijn.',
        'fr': 'Le musulman est celui dont les musulmans sont à l\'abri de sa langue et de sa main.',
        'es': 'El musulmán es aquel de cuya lengua y mano los demás musulmanes están a salvo.',
      },
      source: 'Sahih al-Bukhari 10',
      narrator: 'Abdullah ibn Amr (RA)',
    ),
    HadithModel(
      arabic: 'لَا تَغْضَبْ',
      translations: {
        'en': 'Do not get angry.',
        'tr': 'Kızma!',
        'ar': 'لا تغضب',
        'ru': 'Не гневайся.',
        'hi': 'गुस्सा मत करो।',
        'id': 'Jangan marah.',
        'zh': '不要生气。',
        'de': 'Werde nicht zornig.',
        'nl': 'Word niet boos.',
        'fr': 'Ne te mets pas en colère.',
        'es': 'No te enfades.',
      },
      source: 'Sahih al-Bukhari 6116',
      narrator: 'Abu Hurairah (RA)',
    ),
    HadithModel(
      arabic: 'الدَّالُّ عَلَى الْخَيْرِ كَفَاعِلِهِ',
      translations: {
        'en': 'The one who guides to good is like the one who does it.',
        'tr': 'Hayra yol gösteren, onu yapan gibidir.',
        'ar': 'الدال على الخير كفاعله',
        'ru': 'Указывающий на благое подобен совершающему его.',
        'hi': 'नेकी की राह दिखाने वाला उसे करने वाले जैसा है।',
        'id': 'Orang yang menunjukkan kebaikan seperti orang yang melakukannya.',
        'zh': '指引善行的人如同做善行的人。',
        'de': 'Wer zum Guten führt, ist wie derjenige, der es tut.',
        'nl': 'Degene die naar het goede leidt, is als degene die het doet.',
        'fr': 'Celui qui guide vers le bien est comme celui qui le fait.',
        'es': 'Quien guía hacia el bien es como quien lo hace.',
      },
      source: 'Jami at-Tirmidhi 2670',
      narrator: 'Anas ibn Malik (RA)',
    ),
    HadithModel(
      arabic: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ طَرِيقًا إِلَى الْجَنَّةِ',
      translations: {
        'en': 'Whoever takes a path seeking knowledge, Allah will make easy for him a path to Paradise.',
        'tr': 'Kim ilim aramak icin bir yola girerse, Allah ona cennete giden yolu kolaylastirir.',
        'ar': 'من سلك طريقا يلتمس فيه علما سهل الله له طريقا إلى الجنة',
        'ru': 'Кто идёт по пути в поисках знаний, тому Аллах облегчит путь в Рай.',
        'hi': 'जो ज्ञान की खोज में रास्ता अपनाता है, अल्लाह उसके लिए जन्नत का रास्ता आसान कर देता है।',
        'id': 'Siapa yang menempuh jalan mencari ilmu, Allah mudahkan baginya jalan ke surga.',
        'zh': '谁踏上求知之路，真主将为他通往天堂的路变得容易。',
        'de': 'Wer einen Weg einschlägt, um Wissen zu suchen, dem erleichtert Allah den Weg zum Paradies.',
        'nl': 'Wie een pad bewandelt op zoek naar kennis, Allah maakt het pad naar het Paradijs gemakkelijk voor hem.',
        'fr': 'Quiconque emprunte un chemin pour chercher la science, Allah lui facilite un chemin vers le Paradis.',
        'es': 'Quien recorre un camino buscando conocimiento, Allah le facilitara un camino al Paraiso.',
      },
      source: 'Sahih Muslim 2699',
      narrator: 'Abu Hurairah (RA)',
    ),
    HadithModel(
      arabic: 'لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
      translations: {
        'en': 'None of you truly believes until he loves for his brother what he loves for himself.',
        'tr': 'Sizden biriniz kendisi icin sevdigini kardes icin sevmedikce iman etmis olmaz.',
        'ar': 'لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه',
        'ru': 'Не уверует никто из вас, пока не полюбит для брата то, что любит для себя.',
        'hi': 'तुम में से कोई तब तक मोमिन नहीं जब तक अपने भाई के लिए वह न चाहे जो अपने लिए चाहता है।',
        'id': 'Tidak beriman seseorang sampai ia mencintai saudaranya seperti mencintai dirinya.',
        'zh': '你们中没有人是真正的信士，直到他为兄弟喜爱他为自己所喜爱的。',
        'de': 'Keiner von euch glaubt wahrhaft, bis er fuer seinen Bruder liebt, was er fuer sich selbst liebt.',
        'nl': 'Niemand van jullie gelooft werkelijk totdat hij voor zijn broeder wenst wat hij voor zichzelf wenst.',
        'fr': 'Aucun de vous ne croit veritablement tant qu\'il n\'aime pour son frere ce qu\'il aime pour lui-meme.',
        'es': 'Ninguno de vosotros cree verdaderamente hasta que ame para su hermano lo que ama para si mismo.',
      },
      source: 'Sahih al-Bukhari 13',
      narrator: 'Anas ibn Malik (RA)',
    ),
    HadithModel(
      arabic: 'الطُّهُورُ شَطْرُ الْإِيمَانِ',
      translations: {
        'en': 'Cleanliness is half of faith.',
        'tr': 'Temizlik imanin yarisidir.',
        'ar': 'الطهور شطر الإيمان',
        'ru': 'Чистота — половина веры.',
        'hi': 'सफाई आधा ईमान है।',
        'id': 'Kebersihan adalah separuh iman.',
        'zh': '清洁是信仰的一半。',
        'de': 'Reinheit ist die Haelfte des Glaubens.',
        'nl': 'Reinheid is de helft van het geloof.',
        'fr': 'La purete est la moitie de la foi.',
        'es': 'La limpieza es la mitad de la fe.',
      },
      source: 'Sahih Muslim 223',
      narrator: 'Abu Malik al-Ash\'ari (RA)',
    ),
    HadithModel(
      arabic: 'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
      translations: {
        'en': 'The best of you are those who learn the Quran and teach it.',
        'tr': 'En hayirliniz Kuran\'i ogrenen ve ogretendir.',
        'ar': 'خيركم من تعلم القرآن وعلمه',
        'ru': 'Лучшие из вас — те, кто изучает Коран и обучает ему.',
        'hi': 'तुम में सबसे अच्छा वह है जो कुरआन सीखे और सिखाए।',
        'id': 'Sebaik-baik kalian adalah yang belajar Al-Quran dan mengajarkannya.',
        'zh': '你们中最好的人是学习古兰经并教授它的人。',
        'de': 'Die Besten unter euch sind diejenigen, die den Quran lernen und lehren.',
        'nl': 'De besten onder jullie zijn degenen die de Koran leren en onderwijzen.',
        'fr': 'Les meilleurs d\'entre vous sont ceux qui apprennent le Coran et l\'enseignent.',
        'es': 'Los mejores de vosotros son los que aprenden el Coran y lo ensenan.',
      },
      source: 'Sahih al-Bukhari 5027',
      narrator: 'Uthman ibn Affan (RA)',
    ),
    HadithModel(
      arabic: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
      translations: {
        'en': 'Whoever believes in Allah and the Last Day, let him speak good or remain silent.',
        'tr': 'Allah\'a ve ahiret gunune iman eden ya hayir soylesin ya sussun.',
        'ar': 'من كان يؤمن بالله واليوم الآخر فليقل خيرا أو ليصمت',
        'ru': 'Кто верит в Аллаха и Судный день, пусть говорит благое или молчит.',
        'hi': 'जो अल्लाह और आखिरत के दिन पर ईमान रखता है, वह अच्छी बात कहे या चुप रहे।',
        'id': 'Siapa yang beriman kepada Allah dan hari akhir, hendaklah berkata baik atau diam.',
        'zh': '凡信仰真主和末日的人，要么说好话，要么保持沉默。',
        'de': 'Wer an Allah und den Juengsten Tag glaubt, soll Gutes sagen oder schweigen.',
        'nl': 'Wie in Allah en de Laatste Dag gelooft, laat hem goed spreken of zwijgen.',
        'fr': 'Quiconque croit en Allah et au Jour dernier, qu\'il dise du bien ou qu\'il se taise.',
        'es': 'Quien crea en Allah y el Ultimo Dia, que diga algo bueno o que calle.',
      },
      source: 'Sahih al-Bukhari 6018',
      narrator: 'Abu Hurairah (RA)',
    ),
  ];
}
